// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (name, url, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, url, user_id, created_at, updated_at
`

type CreateFeedParams struct {
	Name      string
	Url       string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.Name,
		arg.Url,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getALLFeeds = `-- name: GetALLFeeds :many
SELECT
  f.name AS name,
  f.url AS url,
  u.name AS username,
  f.created_at as created_at,
  f.updated_at as updated_at
FROM feeds f
INNER JOIN users u ON f.user_id = u.id
ORDER BY f.created_at DESC
`

type GetALLFeedsRow struct {
	Name      string
	Url       string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetALLFeeds(ctx context.Context) ([]GetALLFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getALLFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetALLFeedsRow
	for rows.Next() {
		var i GetALLFeedsRow
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
